---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_msg: Lock deployment in demo stage
    flux.weave.works/locked_user: DeepZimio <deepo@zimio.com>
  name: podinfo
  namespace: customer-one
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: customer-one
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: customer-one