---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_msg: Lock deployment in prod stage
    flux.weave.works/locked_user: DeepZimio <deepo@zimio.com>
  name: tenant-one
  namespace: customer-one-prod